packages:
  - examples/**
  - docs
  - client
catalog:
  nuxt: ^4.4.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-inspect: ^11.3.3
  vite-plus: ^0.1.18
  vitest: npm:@voidzero-dev/vite-plus-test@latest

ignoreWorkspaceRootCheck: true
overrides:
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
shamefullyHoist: true
onlyBuiltDependencies:
  - esbuild
