packages:
  - examples/**
  - docs
  - client

catalog:
  nuxt: ^4.5.2
  vite-plugin-inspect: ^12.0.2

catalogs:
  vite-plus:
    'vite': 'npm:@voidzero-dev/vite-plus-core@0.3.3'
    'vite-plus': '0.3.3'
    'vitest': '4.1.11'

ignoreWorkspaceRootCheck: true

overrides:
  vite: 'catalog:vite-plus'
  vitest: 'catalog:vite-plus'

shamefullyHoist: true
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  sharp: true
  vue-demi: true
