/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefaultTag: typeof import('./.vitepress/components/DefaultTag.vue')['default']
    HomePage: typeof import('./.vitepress/components/HomePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypeTag: typeof import('./.vitepress/components/TypeTag.vue')['default']
  }
}
