name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 22
          cache: true

      - name: Check
        run: vp check

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [20.x, 22.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Setup Vite+ ${{ matrix.node }}
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: ${{ matrix.node }}
          cache: true

      - name: Build
        run: vp pack

      - name: Test
        run: vp test
